<h2 class="visually-hidden">Store address</h2>
<a class="footer-logo"> <img src="images/footer-logo.png" width="220.81"
	height="69.68" alt="Logo The Board Basement">
</a>
<p class="info-text">
	<b>WE ARE OPEN:</b> 9:00 - 17:00 MON - SAT We are closed on Sundays
</p>
<p class="info-text">
	<b>OUR ADDRESS IS:</b><br>The Board Basement, 4 Bridford Road, Marsh
	Barton, Exeter, Devon, EX2 8QX, United Kingdom
</p>
<p class="info-text">
	<b>OUR PHONE NUMBER IS:</b>01392 275 256
</p>