<div class="payment-wrapper">
	<div class="payment-title-wrapper">
		<img class="payment-title-img" src="<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('images/payment-title.png'); ?>"
			width="13.55" height="16.26">
		<p class="payment-title">SECURE PAYMENT</p>
	</div>
	<ul class="payment-list">
		<li class="payment-item"><img class="payment-item-img"
			src="<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('images/payment-1.jpg'); ?>" width="63.81" height="40.51" alt="Visa"></li>
		<li class="payment-item"><img class="payment-item-img"
			src="<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('images/payment-2.jpg'); ?>" width="63.81" height="40.51"
			alt="MasterCard"></li>
		<li class="payment-item"><img class="payment-item-img"
			src="<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('images/payment-3.jpg'); ?>" width="63.81" height="40.51" alt="PayPal"></li>
		<li class="payment-item"><img class="payment-item-img"
			src="<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('images/payment-4.jpg'); ?>" width="63.81" height="40.51"
			alt="Visa Electron"></li>
		<li class="payment-item"><img class="payment-item-img"
			src="<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('images/payment-5.jpg'); ?>" width="63.81" height="40.51" alt="Sage"></li>
	</ul>
</div>