<h2 class="services-title">CUSTOMER SERVICES</h2>
<nav class="services-navigation">
	<ul class="services-navigation-wrapper">
		<li class="service-item"><a href="#">DELIVERY</a></li>
		<li class="service-item"><a href="#">RETURNS</a></li>
		<li class="service-item"><a href="#">ORDER TRACKING</a></li>
		<li class="service-item"><a href="#">IN-STORE SIGN UP</a></li>
		<li class="service-item"><a href="#">HELP</a></li>
	</ul>
</nav>