<ul class="social-wrapper">
	<li><a class="social-button" href="#"><span class="visually-hidden">Twitter</span><img
			src="<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('images/social-1.png'); ?>" width="41.37" height="47.76" alt="Twitter">
	</a></li>
	<li><a class="social-button" href="#"><span class="visually-hidden">Facebook</span><img
			src="<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('images/social-2.png'); ?>" width="41.37" height="47.76" alt="Facebook"></a></li>
	<li><a class="social-button" href="#"><span class="visually-hidden">Instagram</span><img
			src="<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('images/social-3.png'); ?>" width="41.37" height="47.76"
			alt="Instagram"></a></li>
	<li><a class="social-button" href="#"><span class="visually-hidden">Pinterest</span><img
			src="<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('images/social-4.png'); ?>" width="41.37" height="47.76"
			alt="Pinterest"></a></li>
	<li><a class="social-button" href="#"><span class="visually-hidden">Tumblr</span><img
			src="<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('images/social-5.png'); ?>" width="41.37" height="47.76" alt="Tumblr"></a></li>
</ul>