<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
?>
<?php
/** @var $block \Magento\Framework\View\Element\Template */
/** @var $helper \Magento\Search\Helper\Data */
$helper = $this->helper(\Magento\Search\Helper\Data::class);
?>
<div class="block block-search">
	<div class="block block-title">
		<strong><?= /* @escapeNotVerified */ __('Search') ?></strong>
	</div>
	<div class="block block-content">
		<form class="form minisearch" id="search_mini_form"
			action="<?= /* @escapeNotVerified */ $helper->getResultUrl() ?>"
			method="get">
			<div class="field search">
				<label class="label visually-hidden" for="search" data-role="minisearch-label"> <span><?= /* @escapeNotVerified */ __('Search') ?></span>
				</label>		
					<input id="search"
						data-mage-init='{"quickSearch":{
                                "formSelector":"#search_mini_form",
                                "url":"<?= /* @escapeNotVerified */ $helper->getSuggestUrl()?>",
                                "destinationSelector":"#search_autocomplete"}
                           }'
						type="text"
						name="<?= /* @escapeNotVerified */ $helper->getQueryParamName() ?>"
						value="<?= /* @escapeNotVerified */ $helper->getEscapedQueryText() ?>"
						placeholder="<?= /* @escapeNotVerified */ __('Search our site') ?>"
						class="input-text input-search"
						maxlength="<?= /* @escapeNotVerified */ $helper->getMaxQueryLength() ?>"
						role="combobox" aria-haspopup="false" aria-autocomplete="both"
						autocomplete="off" />
					<div id="search_autocomplete" class="search-autocomplete"></div>
                    <?= $block->getChildHtml() ?>     
			</div>
			<div class="actions">
				<button type="submit"
					title="<?= $block->escapeHtml(__('Search')) ?>"
					class="action search">
					<span><?= /* @escapeNotVerified */ __('Search') ?></span>
				</button>
			</div>
		</form>
	</div>
</div>
