<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Account\AuthorizationLink $block */
$dataPostParam = '';
if ($block->isLoggedIn()) {
    $dataPostParam = sprintf(" data-post='%s'", $block->getPostParams());
}
?>

<a <?= /* @noEscape */ $block->getLinkAttributes() ?>
	<?= /* @noEscape */ $dataPostParam ?>>
    <img src="<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('images/authorization.png'); ?>" width="21.53" height="22.7"
	alt="Authorization">
</a>
