<div class="banners-wrapper">
	<h2 class="visually-hidden">Баннеры</h2>
	<div class="banner-1">
		<img src="<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('images/wakeboarding.jpg'); ?>" width="1132" height="703.06">
		<p class="banner-1-label-1">WAKE UP</p>
		<p class="banner-1-label-2">2018 BOARDS NOW IN STOCK</p>
		<a href="#" class="button shop-banner-1">SHOP NOW</a>
	</div>
	<div class="banners-right-wrapper">
		<div class="banner-2">
			<img src="<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('images/banner-2.jpg'); ?>" width="554.7" height="341.73">
			<p class="banner-2-label-1">
				PACK<br>IT IN
			</p>
			<a href="#" class="button shop-banner-2">SHOP NOW</a>
		</div>
		<div class="banner-3">
			<img src="<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('images/banner-3.jpg'); ?>" width="554.7" height="341.73">
			<p class="banner-3-label-1">BONFIRE</p>
			<p class="banner-3-label-2">TECHNICAL OUTERWEAR</p>
			<a href="#" class="button button shop-banner-3">SHOP NOW</a>
		</div>
	</div>
</div>