<h2 class="brand-title">SHOP BY BRAND</h2>
<div class="brand-wrapper">
	<img class="brand-item" src="<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('images/brand-1.png'); ?>" width="164"
		height="56" alt="Acme Co"> <img class="brand-item"
		src="<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('images/brand-2.png'); ?>" width="164" height="56" alt="Acme Co"> <img
		class="brand-item" src="<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('images/brand-3.png'); ?>" width="164" height="56"
		alt="Acme Co"> <img class="brand-item" src="<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('images/brand-4.png'); ?>"
		width="164" height="56" alt="Acme Co"> <img class="brand-item"
		src="<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('images/brand-5.png'); ?>" width="164" height="56" alt="Acme Co"> <img
		class="brand-item" src="<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('images/brand-6.png'); ?>" width="164" height="56"
		alt="Acme Co"> <img class="brand-item" src="<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('images/brand-7.png'); ?>"
		width="164" height="56" alt="Acme Co"> <img class="brand-item"
		src="<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('images/brand-8.png'); ?>" width="164" height="56" alt="Acme Co"> <img
		class="brand-item" src="<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('images/brand-9.png'); ?>" width="164" height="56"
		alt="Acme Co"> <img class="brand-item" src="<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('images/brand-10.png'); ?>"
		width="164" height="56">
</div>
<div class="send-brands-wrapper">
	<a href="#" class="button send-brands">VIEW ALL BRANDS</a>
</div>