<h2 class="categories-title">CATEGORIES</h2>
<div class="categories-wrapper">
	<a class="category-item" href="#"><span class="category-item-wrapper">
			<img src="<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('images/snowboard_ski.jpg'); ?>" width="329.03" height="136.43">
	</span> <span class="category-label">SNOWBOARD & SKI</span></a> <a
		class="category-item" href="#"> <span class="category-item-wrapper"><img
			src="<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('images/surf.jpg'); ?>" width="329.03" height="136.43"></span> <span
		class="category-label">SURF</span>
	</a> <a class="category-item" href="#"><span
		class="category-item-wrapper"> <img src="<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('images/wake.jpg'); ?>"
			width="329.03" height="136.43"></span> <span class="category-label">WAKE</span>
	</a> <a class="category-item" href="#"> <span
		class="category-item-wrapper"><img src="<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('images/skate.jpg'); ?>"
			width="329.03" height="136.43"></span> <span class="category-label">SKATE</span>
	</a> <a class="category-item" href="#"> <span
		class="category-item-wrapper"><img src="<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('images/bike.jpg'); ?>"
			width="329.03" height="136.43"></span> <span class="category-label">BIKE</span>
	</a> <a class="category-item" href="#"> <span
		class="category-item-wrapper"><img src="<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('images/footwear.jpg'); ?>"
			width="329.03" height="136.43"></span> <span class="category-label">FOOTWEAR</span>
	</a> <a class="category-item" href="#"> <span
		class="category-item-wrapper"><img src="<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('images/bags_luggage.jpg'); ?>"
			width="329.03" height="136.43"></span> <span class="category-label">BAGS
			& LUGGAGE</span>
	</a> <a class="category-item" href="#"> <span
		class="category-item-wrapper"><img src="<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('images/mens.jpg'); ?>"
			width="329.03" height="136.43"> </span><span class="category-label">MENS</span>
	</a> <a class="category-item" href="#"> <span
		class="category-item-wrapper"><img src="<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('images/womens.jpg'); ?>"
			width="329.03" height="136.43"></span> <span class="category-label">WOMENS</span>
	</a> <a class="category-item" href="#"> <span
		class="category-item-wrapper"><img src="<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('images/clearance.jpg'); ?>"
			width="329.03" height="136.43"> </span><span class="category-label">CLEARANCE</span>
	</a>
</div>