<h2 class="new-stuff-title">NEW STUFF</h2>
<div class="cycle-slideshow" data-cycle-fx=carousel
	data-cycle-timeout=5000 data-cycle-carousel-visible=6
	data-cycle-pager="#pager" data-cycle-carousel-fluid=true
	data-cycle-slides="div.item-wrapper">
	<div class="item-wrapper">
		<div class="new-stuff-item">
			<div class="new-stuff-wrapper">
				<img class="new-stuff-img"
					src="<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('images/new-stuff-1.png'); ?>"
					width="267.26" height="288.45">
				<p class="mark-sale">SALE</p>
			</div>
			<p class="item-info">
				<span class="name-item">K2</span> Northern Lite Womens Split
				Snowboard Package 152Cm 2018
			</p>
			<div class="prise-wrapper">
				<p class="item-prise">£123.45</p>
				<p class="item-prise-rrp">RRP £234.56</p>
			</div>
			<div class="reviews-favorite-wrapper">
				<a class="item-reviews"><img
					src="<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('images/item-reviews.png'); ?>"
					width="21.93" height="20.96"></a> <a class="item-favorite"><img
					src="<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('images/item-favorite.png'); ?>"
					width="19.14" height="17.72"></a>
			</div>
		</div>
	</div>
	<div class="item-wrapper">
		<div class="new-stuff-item">
			<div class="new-stuff-wrapper">
				<img class="new-stuff-img"
					src="<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('images/new-stuff-2.png'); ?>"
					width="267.26" height="288.45"> <img class="free-postage"
					src="<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('images/free-postage.png'); ?>"
					width="68.08" height="58.96">
				<p class="mark-new">NEW IN</p>
			</div>
			<p class="item-info">
				<span class="name-item">Dakine</span> Revival Kit S Cortez
			</p>
			<div class="prise-wrapper">
				<p class="item-prise">£123.45</p>
				<p class="item-prise-rrp">RRP £234.56</p>
			</div>
			<div class="reviews-favorite-wrapper">
				<a class="item-reviews"><img src="<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('images/item-reviews.png'); ?>"
					width="21.93" height="20.96"></a> <a class="item-favorite"><img
					src="<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('images/item-favorite.png'); ?>"
					width="19.14" height="17.72"></a>
			</div>
		</div>
	</div>
	<div class="item-wrapper">
		<div class="new-stuff-item">
			<div class="new-stuff-wrapper">
				<img class="new-stuff-img"
					src="<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('images/new-stuff-3.png'); ?>"
					width="267.26" height="288.45">
			</div>
			<p class="item-info">
				<span class="name-item">Oakley</span> Fall Line Goggle 2018 Canteen
				Jade Prizm Jade
			</p>
			<div class="prise-wrapper">
				<p class="item-prise">£123.45</p>
				<p class="item-prise-rrp">RRP £234.56</p>
			</div>
			<div class="reviews-favorite-wrapper">
				<a class="item-reviews"><img src="<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('images/item-reviews.png'); ?>"
					width="21.93" height="20.96"></a> <a class="item-favorite"><img
					src="<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('images/item-favorite.png'); ?>"
					width="19.14" height="17.72"></a>
			</div>
		</div>
	</div>
	<div class="item-wrapper">
		<div class="new-stuff-item">
			<div class="new-stuff-wrapper">
				<img class="new-stuff-img"
					src="<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('images/new-stuff-4.png'); ?>"
					width="267.26" height="288.45">
			</div>
			<p class="item-info">
				<span class="name-item">Dakine</span> Mens Seaboard Hat Black
			</p>
			<div class="prise-wrapper">
				<p class="item-prise">£123.45</p>
				<p class="item-prise-rrp">RRP £234.56</p>
			</div>
			<div class="reviews-favorite-wrapper">
				<a class="item-reviews"><img
					src="<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('images/item-reviews.png'); ?>"
					width="21.93" height="20.96"></a> <a class="item-favorite"><img
					src="<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('images/item-favorite.png'); ?>"
					width="19.14" height="17.72"></a>
			</div>
		</div>
	</div>
	<div class="item-wrapper">
		<div class="new-stuff-item">
			<div class="new-stuff-wrapper">
				<img class="new-stuff-img"
					src="<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('images/new-stuff-5.png'); ?>"
					width="267.26" height="288.45">
			</div>
			<p class="item-info">Bent Metal Transfer Snowboard Bindings 2018</p>
			<div class="prise-wrapper">
				<p class="item-prise">£123.45</p>
				<p class="item-prise-rrp">RRP £234.56</p>
			</div>
			<div class="reviews-favorite-wrapper">
				<a class="item-reviews"><img
					src="<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('images/item-reviews.png'); ?>"
					width="21.93" height="20.96"></a> <a class="item-favorite"><img
					src="<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('images/item-favorite.png'); ?>" width="19.14" height="17.72"></a>
			</div>
		</div>
	</div>
	<div class="item-wrapper">
		<div class="new-stuff-item">
			<div class="new-stuff-wrapper">
				<img class="new-stuff-img"
					src="<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('images/new-stuff-6.png'); ?>"
					width="267.26" height="288.45">
			</div>
			<p class="item-info">Evolve Skateboards Bamboo Gtx Series All Terrain
				- Black Motors</p>
			<div class="prise-wrapper">
				<p class="item-prise">£123.45</p>
				<p class="item-prise-rrp">RRP £234.56</p>
			</div>
			<div class="reviews-favorite-wrapper">
				<a class="item-reviews"><img
					src="<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('images/item-reviews.png'); ?>"
					width="21.93" height="20.96"></a> <a class="item-favorite"><img
					src="<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('images/item-favorite.png'); ?>"
					width="19.14" height="17.72"></a>
			</div>
		</div>
	</div>
</div>
<div class="cycle-pager" id=pager></div>
<div class="send-new-stuff-wrapper">
	<a href="#" class="button send-new-stuff">VIEW ALL NEW STUFF</a>
</div>
 <script type="text/x-magento-init">
{
    "*": {
        "jquery-3.3.1.min": {},
        "jquery.cycle2": {},
        "jquery.cycle2.carousel": {}
    }
}
</script>
