<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/* @var \Magento\Wishlist\Block\Link $block */
?>
<div class="link wishlist" data-bind="scope: 'wishlist'">
	<a <?= /* @noEscape */$block->getLinkAttributes()?>> <!-- ko if: wishlist().counter -->
		<span data-bind="text: wishlist().counter" class="counter qty"></span>
		<!-- /ko --> <img
		src="<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('images/header-favorite.png'); ?>"
		width="21.53" height="22.7" alt="Favorite">
	</a>
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "wishlist": {
                        "component": "Magento_Wishlist/js/view/wishlist"
                    }
                }
            }
        }
    }

</script>
